all: main producer consumer
main: main.cpp
	g++ -o main main.cpp
producer: producer.cpp
	g++ -o producer producer.cpp
consumer: consumer.cpp
	g++ -o consumer consumer.cpp
clean:
	rm -f main producer consumer